### ISSUE TITLE
Рефакторинг ConnectionService

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#63]
В ветке experimental был начат рефакторинг фонового процесса. Изменения обширные, поэтому потребуется их тщательное тестирование.

Основные задачи:
- [x] Вынести AsyncTask из DebugActivity в отдельный Service (AuthService)
- [x] Переделать ConnectionService из IntentService в обычный Service
- [x] Разбить ConnectionService на несколько задач, которые могут запускаться в любом порядке
- [x] Слежение за Wi-Fi в отдельном потоке (WiFiMonitorTask): остановка сервиса при отключении
- [x] Слежение за соединением с интернетом (NetMonitorTask): перезапуск подключения при ошибке
- [x] Моментальное завершение сервиса при смахивании любого уведомления
- [x] Запуск с ярлыка: пропуск этапа с ожиданием IP
- [x] Использование AuthService как части ConnectionService (binding)

Проблемы:
- [ ] [Одновременная работа ConnectionService и DebugActivity невозможна](https://github.com/TheDrHax/mosmetro-android/issues/63#issuecomment-249699382)
- [ ] [Отключение от Wi-Fi не всегда определяется в WiFiMonitorTask](https://github.com/TheDrHax/mosmetro-android/issues/63#issuecomment-249700818)
- [x] [Переподключение к Wi-Fi глючит при нахождении в двух сетях](https://github.com/TheDrHax/mosmetro-android/issues/63#issuecomment-250736636)
- [ ] Не пытаться бесконечно подключаться к сбойной точке доступа (запоминать последний MAC)

**Comment by TheDrHax** [comment]
* [ ] Одновременная работа ConnectionService и DebugActivity невозможна

Текущий принцип работы с новым AuthService не позволяет одновременно подключать его к двум модулям. При открытии ручного подключения при работающем фоновом сервисе возможны непредсказуемые последствия, например часть лога уходит в сервис, а другая показывается на экране.

Возможные решения:
* Отделить AuthTask от AuthService и не использовать привязку AuthService к ConnectionService
* Блокировать ConnectionService при открытом DebugActivity
* Блокировать DebugActivity при работающем ConnectionService и отображать лог из него

**Comment by TheDrHax** [comment]
* [ ] Отключение от Wi-Fi не всегда определяется в WiFiMonitorTask

При постепенном снижении мощности сигнала Wi-Fi, Android может не определить момент полного отключения от сети. Это проявляется, например, в ожидании IP адреса, когда сеть уже отключена. В Cyanogen OS это также заметно по "зависшим" профилям системы.

Возможные решения:
* [SupplicantState](https://developer.android.com/reference/android/net/wifi/SupplicantState.html)
* [DetailedState](https://developer.android.com/reference/android/net/NetworkInfo.DetailedState.html)

**Comment by TheDrHax** [comment]
### Переподключение к Wi-Fi глючит при нахождении в двух сетях

При нахождении в области покрытия сразу двух поддерживаемых сетей Android может решить подключиться к менее глючной сети. Он отключается от текущей сети и подключается к новой, WiFiMonitorTask замечает это и пытается подключиться обратно. Получается бесконечный цикл, проявляющийся в частой смене сети и спаме уведомлениями (несколько раз в секунду).

**Comment by TheDrHax** [comment]
Работа над новым фоновым процессом перенесена в ветку new_service. Ветка experimental будет использоваться, как и раньше, для кратковременных отклонений от ветки master.

**Comment by TheDrHax** [comment]
Этот тикет тоже довольно сильно устарел. ConnectionService с тех пор сильно изменился и теперь задача избавления от багов уже не кажется такой сложной. Ветку new_service я пока оставлю, но вряд-ли она теперь пригодится.
